name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Make build script executable
        run: chmod +x build.sh

      - name: Build project
        run: ./build.sh

      - name: Tests
        run: ctest --test-dir build --output-on-failure
